=head1 FTN-Database To Do


=head2 General

Move code repository information and the distribution archive information
from the README file to elsewhere.  POD in main module?  website and/or wiki?

Investigate the usage of SQL::Statement. Possibly at least use it for testing?


=head2 FTN::Database

The use of special characters like periods in table names is a more general
issue where it is not a good idea to use them at all.  Redo the comments in
scripts and modules regarding that, to generalize it.  (Derive function to
validate it and add th at to the FTN::Database module?)


=head2 FTN::Database::Nodelist

Need to update the definition of the timestamp field, and/or what the default 
for it is.  Currently "now" is the default, but that results in the word 'now'
being inserted into the field instead of a date/time timestamp (at least, in
a PostgreSQL database).  Check how the various databases handle timestamp fields
again.


=head2 FTN:Database::Echolist

Create an FTN Database module for echolists which: Defines an Echolist table,
default name "Echolist"?  Basic table would consist of (at least) the following
fields:  name, description, source. Also include fields like: moderator?


=head2 FTN:Database::Forum

Create an FTN Database module for message forum or conference areas which: Defines
a forum/conference table, default name "Forum"?  Derive initial definition of the
table from that used in the areatable.pl script in the bbsdbpl application.


=head1 SEE ALSO

L<FTN::Database>, L<FTN::Database::Nodelist>


=head1 AUTHOR

Robert James Clay, C<< <jame at rocasa.us> >>

=head1 COPYRIGHT & LICENSE

Copyright 2012 Robert James Clay, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut




